---
apiVersion: batch/v1
kind: Job
metadata:
  name: kata-verify
spec:
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - echo
        - OK
        image: busybox
        name: kata-verify
        resources: {}
      restartPolicy: Never
      runtimeClassName: kata
